sudo: required
services:
  - docker

before_install:
  - docker build -t nesspll/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nesspll/docker-react npm run test


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "react-docker"
  env: "ReactDockerr-env"
  bucket_name: "elasticbeanstalk-us-west-2-568283627415"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

